// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package dbsqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type RiverJobState string

const (
	RiverJobStateAvailable RiverJobState = "available"
	RiverJobStateCancelled RiverJobState = "cancelled"
	RiverJobStateCompleted RiverJobState = "completed"
	RiverJobStateDiscarded RiverJobState = "discarded"
	RiverJobStatePending   RiverJobState = "pending"
	RiverJobStateRetryable RiverJobState = "retryable"
	RiverJobStateRunning   RiverJobState = "running"
	RiverJobStateScheduled RiverJobState = "scheduled"
)

func (e *RiverJobState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RiverJobState(s)
	case string:
		*e = RiverJobState(s)
	default:
		return fmt.Errorf("unsupported scan type for RiverJobState: %T", src)
	}
	return nil
}

type NullRiverJobState struct {
	RiverJobState RiverJobState
	Valid         bool // Valid is true if RiverJobState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRiverJobState) Scan(value interface{}) error {
	if value == nil {
		ns.RiverJobState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RiverJobState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRiverJobState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RiverJobState), nil
}

type RiverJob struct {
	ID           int64
	Args         []byte
	Attempt      int16
	AttemptedAt  pgtype.Timestamptz
	AttemptedBy  []string
	CreatedAt    pgtype.Timestamptz
	Errors       [][]byte
	FinalizedAt  pgtype.Timestamptz
	Kind         string
	MaxAttempts  int16
	Metadata     []byte
	Priority     int16
	Queue        string
	State        RiverJobState
	ScheduledAt  pgtype.Timestamptz
	Tags         []string
	UniqueKey    []byte
	UniqueStates pgtype.Bits
}

type RiverJobDeadLetter struct {
	ID             int64
	Args           []byte
	Attempt        int16
	AttemptedAt    pgtype.Timestamptz
	AttemptedBy    []string
	CreatedAt      pgtype.Timestamptz
	Errors         [][]byte
	FinalizedAt    pgtype.Timestamptz
	Kind           string
	MaxAttempts    int16
	Metadata       []byte
	Priority       int16
	Queue          string
	State          RiverJobState
	ScheduledAt    pgtype.Timestamptz
	Tags           []string
	UniqueKey      []byte
	UniqueStates   pgtype.Bits
	DeadLetteredAt pgtype.Timestamptz
}

type RiverJobSequence struct {
	ID        int64
	Key       string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type RiverPeriodicJob struct {
	ID        string
	CreatedAt pgtype.Timestamptz
	NextRunAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type RiverProducer struct {
	ID         int64
	ClientID   string
	QueueName  string
	MaxWorkers int32
	Metadata   []byte
	PausedAt   pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type RiverQueue struct {
	Name      string
	CreatedAt pgtype.Timestamptz
	Metadata  []byte
	PausedAt  pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type RiverWorkflow struct {
	ID                  string
	Name                pgtype.Text
	State               string
	Metadata            []byte
	CurrentAttempt      int32
	WaitEvalCursorJobID pgtype.Int8
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	FinalizedAt         pgtype.Timestamptz
}

type RiverWorkflowAttempt struct {
	WorkflowID   string
	Attempt      int32
	ResetHistory bool
	RetryMode    string
	TriggeredBy  []byte
	CreatedAt    pgtype.Timestamptz
}

type RiverWorkflowAttemptTask struct {
	WorkflowID   string
	Attempt      int32
	Task         string
	JobID        int64
	State        RiverJobState
	AttemptCount int32
	Errors       [][]byte
	Metadata     []byte
	FinalizedAt  pgtype.Timestamptz
}

type RiverWorkflowSignal struct {
	ID             int64
	WorkflowID     string
	Attempt        int32
	Key            string
	IdempotencyKey string
	Payload        []byte
	Metadata       []byte
	Source         []byte
	CreatedAt      pgtype.Timestamptz
}

type RiverWorkflowTimer struct {
	WorkflowID string
	NextFireAt pgtype.Timestamptz
}

type RiverWorkflowWorklist struct {
	ID         int64
	WorkflowID string
	Reason     int16
	CreatedAt  pgtype.Timestamptz
}
